#!/bin/bash

# Discussion, issues and change requests at:
#   https://github.com/nodesource/distributions
#
# Script to install NodeSource repo onto a Debian or Ubuntu system.
#
# Run as root or insert `sudo` before `bash`:
#
# curl -sL https://deb.nodesource.com/setup | bash -
#   or
# wget -qO- https://deb.nodesource.com/setup | bash -
#

print_status() {
    echo ""
    echo "## $*"
    echo ""
}

bail() {
    echo "Error executing command, exiting"
    exit 1
}

exec_cmd() {
    echo "+ ${@}"
    sh -c "${@}" || bail
}

PRE_INSTALL_PKGS=""

# Check that HTTPS transport is available to APT
# (Check snaked from: https://get.docker.io/ubuntu/)

if [ ! -e /usr/lib/apt/methods/https ]; then
    PRE_INSTALL_PKGS="apt-transport-https ${PRE_INSTALL_PKGS}"
fi

if [ ! -x /usr/bin/lsb_release ]; then
    PRE_INSTALL_PKGS="lsb-release ${PRE_INSTALL_PKGS}"
fi

if [ ! -x /usr/bin/curl ] && [ ! -x /usr/bin/wget ]; then
    PRE_INSTALL_PKGS="curl ${PRE_INSTALL_PKGS}"
fi

if [ "X${PRE_INSTALL_PKGS}" != "X" ]; then
    print_status "Installing packages required for setup: ${PRE_INSTALL_PKGS}..."
    exec_cmd "apt-get update"
    exec_cmd "apt-get install -y $PRE_INSTALL_PKGS"
fi

DISTRO=$(lsb_release -c -s)

check_alt() {
    if [ "x${DISTRO}" == "x${2}" ]; then
        echo ""
        echo "## You seem to be using ${1} version \"${DISTRO}\"."
        echo "## This maps to ${3} \"${4}\"... Adjusting for you..."
        DISTRO="${4}"
    fi
}

check_alt "Linux Mint"   "qiana" "Ubuntu" "trusty"
check_alt "Linux Mint"   "maya"  "Ubuntu" "precise"
check_alt "elementaryOS" "luna"  "Ubuntu" "trusty"

if [ -f "/etc/apt/sources.list.d/chris-lea-node_js-$DISTRO.list" ]; then
    print_status "Removing Launchpad PPA Repository for NodeJS..."

    exec_cmd "add-apt-repository -y -r ppa:chris-lea/node.js"
    exec_cmd "rm -f /etc/apt/sources.list.d/chris-lea-node_js-$DISTRO.list"
fi

print_status "Adding the NodeSource signing key to your keyring..."

if [ -x /usr/bin/curl ]; then
    exec_cmd "curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -"
elif [ -x /usr/bin/wget ]; then
    exec_cmd "wget -qO- https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -"
else
    echo "ERROR: Need either curl or wget installed to run this script! Exiting..."
    exit 1
fi

print_status "Creating apt sources list file for the NodeSource repo..."

exec_cmd "echo 'deb https://deb.nodesource.com/node $DISTRO main' > /etc/apt/sources.list.d/nodesource.list"
exec_cmd "echo 'deb-src https://deb.nodesource.com/node $DISTRO main' >> /etc/apt/sources.list.d/nodesource.list"

print_status "Running 'apt-get update' for you..."

exec_cmd "apt-get update"

print_status "Run 'apt-get install nodejs' (as root) to install Node.js and npm"
